### ISSUE TITLE
composer update errror

### ISSUE THREAD

**Issue by tobiasfeldmethwalter** [dachcom-digital/pimcore-dynamic-search#1]
Hello,

when I insert dachcom-digital / search in composer.json and run composer update I get the error message
"The requested package dachcom-digital / search could not be found in any version, there may be a typo in the package name."
What could be the reason?

Also installed are the formbuilder and the lucene-search

thanks for the information

**Comment by pixel81k** [comment]
Hello,

seems there's a typo in the documentation. please use dachcom-digital/dynamic-search - please also be aware, that so far there's no version release, only dev-master

composer require dachcom-digital/dynamic-search:dev-master

https://packagist.org/packages/dachcom-digital/dynamic-search

Thank you and good luck
