### ISSUE TITLE
Pimcore 6 install...

### ISSUE THREAD

**Issue by MustardOnPizza** [dachcom-digital/pimcore-dynamic-search#10]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

It's yelling at me telling me I can only install this on Pimcore 5... Is this right? I thought this extension was going to replace your other lucene search extension? Is 6 not supported yet?

**Comment by jahwood** [comment]
any tricks to install this on Pimcore > V6?

**Comment by dpfaffenbauer** [comment]
that is true: https://github.com/dachcom-digital/pimcore-dynamic-search/blob/master/composer.json#L31

but pretty sure @solverat merges a PR that changes that

**Comment by dpfaffenbauer** [comment]
that is solved

**Comment by Cruiser13** [comment]
@solverat could you add a release for this? At the moment something like this will fail:

> "dachcom-digital/dynamic-search": "~0.6.0",
    "dachcom-digital/dynamic-search-data-provider-trinity": "~0.6.0",
    "dachcom-digital/dynamic-search-index-provider-lucene": "~0.6.0"

And I'd like to use a specific version instead of master.
