### ISSUE TITLE
Need Help on Error Index doesn't exists in the specified directory.

### ISSUE THREAD

**Issue by nandueverurs** [dachcom-digital/pimcore-dynamic-search#17]
HI All 
I tried to use Dynamic Search and I followed all the instructions given in the [ExampleSetup](https://github.com/dachcom-digital/pimcore-dynamic-search/blob/master/docs/0_ExampleSetup.md).
When i tried to navigate to /dynamic-search/default/search. The form got loaded. When i tried to search some text then I get the below error
Error while loading search output channel for "default" context. Error was: Index doesn't exists in the specified directory.
Please help me in resolving this.

PS: I am new to this submitting support issues . Please do not mind if the formats are wrong. 

Thanks
Nandu

**Comment by nandueverurs** [comment]
Can any one help on this

**Comment by polelo** [comment]
Hi all,
@nandueverurs just came across this issue after running the example setup and got the error above. Judging by how long you posted this I'm pretty sure I'm late in helping you but hope this can help others.

My solution was to run this command "bin/console dynamic-search:run". I found this command in the source code under Commands directory. I think this issue can be closed if my solution is the right way to go.

**Comment by nandueverurs** [comment]
Hi @polelo 
I figured this from the source code and worked on it. Thanks much for sharing your finding.
