### ISSUE TITLE
How to get the current version incl. fixes for Pimcore 6 / Symfony 4.4

### ISSUE THREAD

**Issue by kopieMK** [dachcom-digital/pimcore-dynamic-search#22]
Hello. If we install the latest version (0.7.2) from this bundle, we did not get the fixes (#19 ) respective the changes for using with Pimcore 6 / Symfony 4.x.

How to reference in composer.json to get it?

This is what we set in the pimcore composer.json
```
"dachcom-digital/dynamic-search": "~0.7.2",
"dachcom-digital/dynamic-search-data-provider-crawler": "dev-master",
"dachcom-digital/dynamic-search-index-provider-lucene": "dev-master",
```

We also  tried to set "dev-master" on /dynamic-search, but this fails with the following notice:

Your requirements could not be resolved to an installable set of packages.

 Problem 1
    - dachcom-digital/dynamic-search-data-provider-crawler dev-master requires dachcom-digital/dynamic-search ^0.7 -> satisfiable by dachcom-digital/dynamic-search[v0.7.0, v0.7.1, v0.7.2] but these conflict with your requirements or minimum-stability.
    - dachcom-digital/dynamic-search-data-provider-crawler dev-master requires dachcom-digital/dynamic-search ^0.7 -> satisfiable by dachcom-digital/dynamic-search[v0.7.0, v0.7.1, v0.7.2] but these conflict with your requirements or minimum-stability.
    - Installation request for dachcom-digital/dynamic-search-data-provider-crawler dev-master -> satisfiable by dachcom-digital/dynamic-search-data-provider-crawler[dev-master].

**Comment by solverat** [comment]
Since 1.0.0 this shouldn't be an issue anymore.
