### ISSUE TITLE
Add some more events

### ISSUE THREAD

**Issue by ThisIsJustARandomGuy** [dachcom-digital/pimcore-dynamic-search#27]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

I suggest adding a few events in useful places. In my case, I had to modify the search query just before it gets sent. I know that there is the `OutputChannelModifierEventDispatcher` and the `post_result_execute` event but I cannot figure out how to use it. The event is also fired too late for my use case since I needed to modify the Elasticsearch DSL Search object before the `$query->toArray()` call but after the `$query->setSize($limit)` call (`SearchOutputChannel.php` around the lines 138-145), depending on some dynamic values set in a controller.

Since that wasn't possible, I "improved" on the default `SearchOutputChannel` by adding an `EventDispacher` and my required event. This allows me to modify the query at pretty much any stage and makes working with the `OutputChannels` that much easier as well as more dynamic. I can now easily reuse my `FilterDefinitions` in multiple places which was kinda difficult to achieve beforehand. For example, I want to apply a term filter but only when the search is started from some specific place. With my changes that's a three liner while currently I'd have to do convoluted stuff with FilterDefinitions. I realize that this is basically providing a second way to build queries but I think it's useful and different enough from the current way to consider doing. 

I'm basically asking for two things here. I can provide a pull request for the events but I can't help with the docs for the ModifierEvents.

1) Some docs or an example on how to use the `OutputChannelModifierEventDispatcher`. Maybe it can already do what I want - I just can't figure out how to use it without spending too much time. I'd prefer using this to the default Symfony EventDispatcher - simply because it already exists and seems to do what I want. I'd have to add a few events here and there which I could definitely help with by providing a pull request. But as I said, I can't figure out how to listen to the events (if possible).

2) Use the default symfony event system and provide some events at useful stages (e.g. before/after adding items to the index, before/after building the query, before/after dispatching it and so on.). I'd also provide docs for the changes so that #14 gets started at some point.

As a side-note: This is such an awesome and well built package - it's really a shame that the docs are basically non-existing. I've barely figured out how to get it up and running after weeks of stepping through the code with xdebug. Now that I have a working example, I'm sure that next time I'll be able to do the exact same thing in half a day or less. Simply adding a few code pieces would already go a long way. I'd love to provide pull requests for existing features but I'm sure that lots of what I'm doing isn't exactly right.

**Comment by benwalch** [comment]
@ThisIsJustARandomGuy maybe this helps for a first approach?
https://github.com/dachcom-digital/pimcore-dynamic-search/tree/feature/docs

**Comment by solverat** [comment]
Hey @ThisIsJustARandomGuy. First, thanks for your investigation. I know there is a lack of documentation, we're working on it, and it seems to getting better with v2. :) 

Regarding Events: Your mostly talking about the ES index provider, so we should move this discussion over there.

During the concept phase of DynamicSearch we had this one big goal to keep providers and core separately. But we also needed to find a "generic" way of communication between core and, for example an index provider. So for example the lucene and elasticsearch index provider are **completely** different in their principals, but we needed something like a "common denominator". 

However, in elasticsearch I've realized, that there can't be much preconfigured stuff because of the powerful environment, ES and especially the DSL comes with. So there is just a very simple `DsElasticSearchBundle\OutputChannel\SearchOutputChannel` (identifier`elasticsearch_search`).
 If that's not enough, you should create your own:

```yaml
output_channels:
  my_output_channel:
     service: 'App\OutputChannel\MySearchOutputChannel'
```

But in most of my projects, I was able to build my query within the `post_query_build` tag. Since the default `elasticsearch_search` immediately triggers an `post_query_build` after creating the `Search()` object, it's quite easy to generate queries based on different requirements:

```yaml
App\DynamicSearch\OutputChannel\Action\Search\MainSearchAction:
  tags:
      - { name: dynamic_search.output_channel.modifier.action, output_channel_service_identifier: all, action: post_query_build }
```

And my service:

```php
<?php

namespace App\DynamicSearch\OutputChannel\Action\Search;

use DynamicSearchBundle\Event\OutputModifierEvent;
use DynamicSearchBundle\OutputChannel\Allocator\OutputChannelAllocatorInterface;
use DynamicSearchBundle\OutputChannel\Modifier\OutputChannelModifierActionInterface;
use ONGR\ElasticsearchDSL\Query\Compound\BoolQuery;
use ONGR\ElasticsearchDSL\Query\FullText\MatchPhrasePrefixQuery;
use ONGR\ElasticsearchDSL\Query\FullText\MultiMatchQuery;
use ONGR\ElasticsearchDSL\Query\TermLevel\TermQuery;
use ONGR\ElasticsearchDSL\Search;
use Symfony\Component\HttpFoundation\RequestStack;

class MainSearchAction implements OutputChannelModifierActionInterface
{
    protected RequestStack $requestStack;

    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    public function dispatchAction(string $action, OutputChannelAllocatorInterface $outputChannelAllocator, OutputModifierEvent $event): OutputModifierEvent
    {
        /** @var Search $query */
        $query = $event->getParameter('query');
        $term = $event->getParameter('term');
        $outputChannelName = $outputChannelAllocator->getOutputChannelName();

        if ($outputChannelName !== 'my_output_channel') {
            return $event;
        }

        $locale = $this->requestStack->getMasterRequest()->query->get('locale');
        if ($locale === null) {
            $locale = $this->requestStack->getMasterRequest()->getLocale();
        }

        $boolQuery = new BoolQuery();
        $localeQuery = new TermQuery('locale', $locale);
        $boolQuery->add($localeQuery, BoolQuery::FILTER);

        $this->addMultiMatchQuery($boolQuery, $term);

        $query->addQuery($boolQuery);

        $event->setParameter('query', $query);

        return $event;
    }

    protected function addMultiMatchQuery(BoolQuery $boolQuery, $term): void
    {
        $matchPhraseSkuPrefixQuery = new MatchPhrasePrefixQuery('sku', $term);
        $matchPhraseSkuPrefixQuery->addParameter('boost', 1);

        $multiMatchQuery = new MultiMatchQuery(['title',  'description'], $term);
        $multiMatchQuery->addParameter('fuzziness', 'AUTO');
        $multiMatchQuery->addParameter('prefix_length', 3);

        $shouldQuery = new BoolQuery();
        $shouldQuery->add($matchPhraseSkuPrefixQuery, BoolQuery::SHOULD);
        $shouldQuery->add($multiMatchQuery, BoolQuery::SHOULD);

        $boolQuery->add($shouldQuery);
    }
}
```

I hope this helps!
