### ISSUE TITLE
Wrong type in DefinitionBuilderRegistry::registerFilterDefinition

### ISSUE THREAD

**Issue by ThisIsJustARandomGuy** [dachcom-digital/pimcore-dynamic-search#45]
https://github.com/dachcom-digital/pimcore-dynamic-search/blob/156e80bb3d771c1e0c19cd101d39eb5c5287e18e/src/DynamicSearchBundle/Registry/DefinitionBuilderRegistry.php#L23

The argument shouldn't be a `DocumentDefinitionBuilderInterface` but `FilterDefinitionBuilderInterface`

```PHP
public function registerFilterDefinition(FilterDefinitionBuilderInterface $service): void
```

**Comment by solverat** [comment]
Fixed in #46 and available in [v2.0.1](https://github.com/dachcom-digital/pimcore-dynamic-search/releases/tag/v2.0.1). Thank you!
