### ISSUE TITLE
[Documentation] Misleading id field in "working example"

### ISSUE THREAD

**Issue by gadget60** [dachcom-digital/pimcore-dynamic-search#56]
The working example is kind of misleading:

https://github.com/dachcom-digital/pimcore-dynamic-search/blob/fa975f79278b8f035cd359572f68c8336bd991c1/docs/0_ExampleSetup.md?plain=1#L150

An id field should not be configured manually (at least with the DsLuceneBundle as used in given example)
The reason is: The LuceneHandler relies on an id field that it creates by itself, namely here:
https://github.com/dachcom-digital/pimcore-dynamic-search-index-provider-lucene/blob/de06a1044b0a748db2df6d3b109f204647aa71f7/src/DsLuceneBundle/Service/LuceneHandler.php#L51

LuceneHandler relies on the full qualified index document ids such as "document_en_1234", whereas the 'element_id_extractor' returns the numeric id. Creating an own id field and populating it with the pimcore object/asset/document id's breaks functionality to find documents for updating/deleting. This leads to ever-growing indexes without old index document being deleted.

If you really need the pimcore object/asset/document id either to search for or as search result, you should probably use a field name like "pimcoreid" or similar. 

Hence, the working example should be adjusted to define a field "pimcoreid" instead of "id".

**Comment by solverat** [comment]
Hey @gadget60, you're absolutely right about that. I have no idea what I was thinking while writing that definition…

Fixed: https://github.com/dachcom-digital/pimcore-dynamic-search/commit/96f171d57455595f5bce42eb8a430034e352c705
